{
 "title": "UCS - Rack view",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rack",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"cimc-ucs-power\",\n  tag: \"rack\"\n)"
   },
   {
    "name": "rackforannotation",
    "label": "rack_for_annotation",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"cimc-ucs-power\",\n  tag: \"rack\"\n)"
   },
   {
    "name": "serverforannotation",
    "label": "server_for_annotation",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"cimc-ucs-power\",\n  tag: \"name\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Power per rack",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cimc-ucs-power\" and r._field == \"current_power\" and r.domain == \"Platform\" and r.rack != \"NA\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"rack\"])\n  |> sum(column: \"current_power\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Power per rack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cimc-ucs-power\" and r._field == \"current_power\" and r.domain == \"Platform\" and r.rack != \"NA\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"rack\"])\n  |> truncateTimeColumn(unit: 1h)\n  |> keep(columns: [\"current_power\", \"rack\", \"_time\"])\n  |> sum(column: \"current_power\")\n  |> group(columns: [\"rack\"])"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Power",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "repeat": "rack",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cimc-ucs-power\" and r._field == \"current_power\" and r.domain == \"Platform\" and r.rack == \"${rack}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"name\", \"current_power\"])\n  |> unique(column: \"name\")\n  |> group(columns: [\"rack\"])"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Temperature rear",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "repeat": "rack",
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"cimc-ucs-temperature\" and \n      (\n        //r._field == \"ambient_temp\" or\n        //r._field == \"front_temp\" or\n        r._field == \"rear_temp\"\n      )\n      and r.rack == \"${rack}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"name\", \"ambient_temp\", \"front_temp\", \"rear_temp\"])\n  |> group(columns: [\"rack\"])"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Front temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "repeat": "rack",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"cimc-ucs-temperature\" and \n      (\n        r._field == \"front_temp\"\n      )\n      and r.rack == \"${rack}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with _value: r.front_temp}))\n  |> keep(columns: [\"name\", \"_value\", \"_time\", \"rack\"])\n"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Rear temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "repeat": "rack",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"cimc-ucs-temperature\" and \n      (\n        r._field == \"rear_temp\"\n      )\n      and r.rack == \"${rack}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with _value: r.rear_temp}))\n  |> keep(columns: [\"name\", \"_value\", \"_time\", \"rack\"])\n"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Temperature",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "repeat": "rack",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n      r._measurement == \"cimc-ucs-temperature\" and \n      (\n        r._field == \"ambient_temp\" or\n        r._field == \"front_temp\" or\n        r._field == \"rear_temp\"\n      )\n      and r.rack == \"${rack}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"name\", \"ambient_temp\", \"front_temp\", \"rear_temp\"])\n  |> unique(column: \"name\")\n  |> group(columns: [\"rack\"])"
    }
   ]
  },
  {
   "title": "Servers in rack - ${rack} - Utilization",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "repeat": "rack",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"cimc-ucs-utilization\" and \n      r._field == \"overall_utilization\" and r.rack == \"${rack}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"name\", \"overall_utilization\"])\n  |> unique(column: \"name\")\n  |> group(columns: [\"rack\"])"
    }
   ]
  }
 ]
}