{
 "title": "UCS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_ucs",
    "label": "host_ucs",
    "query": "import \"influxdata/influxdb/v1\"\n\ntag_name = v1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"cimc-ucs-power\",\n  tag: \"name\",\n)\n|> yield()"
   }
  ]
 },
 "panels": [
  {
   "title": "POWER - ${host_ucs}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "host_ucs",
   "targets": [
    {}
   ]
  },
  {
   "title": "Platform, CPU, Memory power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-power\" and \n    (r.domain == \"Platform\" or\n      r.domain == \"CPU\" or\n      r.domain == \"Memory\"\n    ) and \n    r.name == \"${host_ucs}\"\n  )"
    }
   ]
  },
  {
   "title": "Power source - input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-power\" and \n    r._field == \"input\" and\n    r.name == \"${host_ucs}\"\n  )"
    }
   ]
  },
  {
   "title": "Power source - output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-power\" and \n    r._field == \"output\" and\n    r.name == \"${host_ucs}\"\n  )"
    }
   ]
  },
  {
   "title": "TEMPERATURE - ${host_ucs}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "host_ucs",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Unit rack temperature",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-temperature\" and \n    (\n      r._field == \"ambient_temp\" or\n      r._field == \"front_temp\" or\n      r._field == \"rear_temp\"\n    ) and \n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    },
    {
     "title": "CPU temperature",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-temperature\" and \n    r._field == \"temperature\" and r.dn =~ /.*cpu.*/ and\n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    },
    {
     "title": "Memory temperature",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-temperature\" and \n    r._field == \"temperature\" and r.dn =~ /.*mem.*/ and\n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "UTILIZATION - ${host_ucs}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "host_ucs",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overall utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-utilization\" and \n    r._field == \"overall_utilization\" and \n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    },
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-utilization\" and \n    r._field == \"memory_utilization\" and \n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    },
    {
     "title": "IO utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-utilization\" and \n    r._field == \"io_utilization\" and \n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n    r._measurement == \"cimc-ucs-utilization\" and \n    r._field == \"cpu_utilization\" and \n    r.name == \"${host_ucs}\"\n  )"
      }
     ]
    }
   ]
  }
 ]
}