{
 "title": "Raritan PDUs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PDU",
    "query": "\nimport \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"bucket1\",\n  tag: \"name\",\n  predicate: (r) => (r[\"_measurement\"] == \"raritan-pdu\"),\n  start: -duration(v: uint(v: v.timeRangeStop) - uint(v: v.timeRangeStart)),\n)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "PDU ${PDU}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "PDU",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"current\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Unbalanced Current",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"unbalancedCurrent\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"voltage\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Active Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"activePower\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Apparent Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"apparentPower\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Active Energy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MWh" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"activeEnergy\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Line Frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"lineFrequency\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "aggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"activePower\" or r._field == \"apparentPower\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.activePower) / float(v: r.apparentPower))\n   }))\n  |> drop(columns: [\"activePower\", \"apparentPower\"])"
      }
     ]
    },
    {
     "title": "Angle",
     "type": "timeseries",
     "description": "Power factor defines the phase angle between the current and voltage waveforms, where I and V are the magnitudes of rms values of the current and voltage. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "query": "import \"math\"\n\nconv_to_degrees = 180.0/math.pi\naggregationWindow = 15m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"raritan-pdu\" and r.name == \"${PDU}\")\n  |> filter(fn: (r) => r._field == \"activePower\" or r._field == \"apparentPower\")\n  |> aggregateWindow(every: aggregationWindow, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    cosine: (float(v: r.activePower) / float(v: r.apparentPower))\n   }))\n  |> map(fn: (r) => ({\n    r with\n    //phaseAngle: math.acos(x: (float(v: r.cosine) )) // Radian\n    phaseAngle: math.acos(x: (float(v: r.cosine) )) * conv_to_degrees // Degrees\n   }))\n  |> drop(columns: [\"activePower\", \"apparentPower\", \"cosine\"])\n"
      }
     ]
    }
   ]
  }
 ]
}