{
 "title": "Bandwidth utilization",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\",\n  tag: \"source\"\n)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Bandwidth underutilization\r\n\r\nHigh bandwidth and low traffic can signal underutilization of interfaces and implicitly of the device. This can translate into energy waste due to powering the said interfaces.\r\n\r\nTo quantify the relation between traffic and power, we represent the PCR (Power consumption ratio).\r\nThis measurement shows the ratio between the rate of power and the rate of data per second. PCR answers the question: _How much power is used for 1 Gbps data rate?_\r\n\r\n<img src=\"https://render.githubusercontent.com/render/math?math=$PCR = \\frac{input\\_power\\_used}{[input | output\\_]data\\_rate} [\\frac{W}{Gbps}]$\"> \r\n\r\n_Note_: A PCR of value N/A signifies minimal traffic, i.e., < 100 Kbps.\r\n\r\n\r\nBelow you can find a list of devices with underutilized bandwidth and their corresponding PCR: the lower the utilization, the worse bandwidth consumption; the higher the PCR, the worse power consumption.\r\n\r\nAn **optimal scenario** from energy perspective represents **high bandwidth utilization** and a **low PCR**."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Berlin-100",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"generate\"\n\npower = 1000.0                              // W\nbps_to_kbps = 1000.0\nkbps_to_gbps = 1000000.0\nnumber_of_kbps = 10000                      // 10 Gbps\nnumber_of_gbps = 1000.0                     // 1 Tbps\nbandwidth = number_of_gbps * kbps_to_gbps   // unit: Kbps; 1000 Gbps = 1 Tbps\ngenerate.from(\n    // number of data points\n    count: 177,\n    // data rate of unit: Kbps; n * 10000 Kbps = n * 10 Gbps\n    fn: (n) => if n % 101 == 0 then number_of_kbps * int(v: bps_to_kbps) else n % 101 * number_of_kbps * int(v: bps_to_kbps),\n    start: -15m,\n    stop: -1s,\n)\n    |> map(fn: (r) => ({r with power: power}))\n    |> map(fn: (r) => ({r with bandwidth: bandwidth}))\n    |> map(fn: (r) => ({r with input_data_rate: float(v: r._value)}))\n    |> map(fn: (r) => ({r with bandwidth_utilization: r.input_data_rate / r.bandwidth}))\n    |> map(fn: (r) => ({r with PCR: r.power / (r.input_data_rate / kbps_to_gbps)}))\n    |> map(fn: (r) => ({r with source: \"Berlin-100\"}))\n    |> drop(columns: [\"_value\", \"bandwidth\", \"power\", \"input_data_rate\"])"
    }
   ]
  },
  {
   "title": "NCS 5xxL",
   "type": "table",
   "description": "Interfaces administratively up / down of type: .*IFT_.*HUNDREDGE, .*IFT_.*FORTY or .*IFT_.*TEN.\nPCR:Wattage per Gbps for interfaces with administrative state up.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/v1\"\r\nimport \"math\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => \r\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\r\n    (r._field == \"total_pwr_output\" or r._field == \"total_out_capacity\") and r._value > 0\r\n    )\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  |> unique(column: \"source\")\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"source\")\r\n\r\nfrom(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\" or r[\"_field\"] == \"input_data_rate\")\r\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\r\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\r\n\r\n  // Take the mean of bandwidth and input_data_rate\r\n  |> window(every: timeInterval)\r\n  |> mean()\r\n\r\n  // Reshape\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> last(column: \"_value\")\r\n  |> group(columns: [\"source\", \"_field\"])\r\n\r\n  // Take the sum of bandwidths and input_data_rate for each device\r\n  |> aggregateWindow(every: timeInterval, fn: sum)\r\n\r\n  // Reshape\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> truncateTimeColumn(unit: timeInterval)\r\n  |> last()\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n\r\n  // Consider only data that has bandwidth greater than 0 and fill missing values of traffic data with 0\r\n  |> filter(fn: (r) => r.bandwidth > 0)\r\n\r\n  // Compute bandwidth utilization [0-1]\r\n  |> map(fn: (r) => ({ r with bandwidth_utilization: float(v: r[\"input_data_rate\"]) / float(v: r[\"bandwidth\"])}))\r\n\r\n  |> drop(columns: [\"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"source\"], desc: true)\r\n  |> yield()"
    },
    {
     "query": "import \"influxdata/influxdb/v1\"\r\nimport \"math\"\r\n\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = from(bucket: \"bucket1\")\r\n    |> range(start: timeRange)\r\n    |> filter(\r\n        fn: (r) => r.device_type != \"cisco-8k\" and r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and r._field == \"total_pwr_output\" and r._value > 0,\r\n    )\r\n    // Trick to enforce grouping by same key of all devices\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            groupingkey: 1,\r\n        }),\r\n    )\r\n    |> group(columns: [\"groupingkey\"])\r\n    |> unique(column: \"source\")\r\n    // Extract a set with the names of the devices\r\n    |> findColumn(fn: (key) => key.groupingkey == 1, column: \"source\")\r\ntype = from(bucket: \"bucket1\")\r\n    |> range(start: timeRange)\r\n    // Check that this device is in the list of devices that we are looking for\r\n    |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n    |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"type\")\r\n    |> filter(fn: (r) => r._value =~ /.*IFT_.*HUNDREDGE.*/ or r._value =~ /.*IFT_.*FORTY.*/ or r._value =~ /.*IFT_.*TEN.*/)\r\n    |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            if_type: if r._field == \"type\" then\r\n                r._value\r\nelse\r\n                \"test\",\r\n        }),\r\n    )\r\n    |> group(columns: [\"interface_name\", \"source\"])\r\n    |> drop(columns: [\r\n        \"_start\",\r\n        \"_stop\",\r\n        \"_field\",\r\n        \"_time\",\r\n        \"_value\",\r\n    ])\r\n    |> distinct(column: \"if_type\")\r\nstate = from(bucket: \"bucket1\")\r\n    |> range(start: timeRange)\r\n    // Check that this device is in the list of devices that we are looking for\r\n    |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n    |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"state\")\r\n    |> filter(fn: (r) => r._value =~ /.*up.*/)\r\n    |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            if_state: if r._field == \"state\" then\r\n                r._value\r\nelse\r\n                \"NA\",\r\n        }),\r\n    )\r\n    |> group(columns: [\"interface_name\", \"source\"])\r\n    |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_time\"])\r\n    |> last()\r\ninterfaces_up = join(\r\n    tables: {d1: state, d2: type},\r\n    on: [\"interface_name\", \"source\"],\r\n)\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            if_state: r._value_d1,\r\n            if_type: r._value_d2,\r\n        }),\r\n    )\r\n    |> drop(columns: [\"_value_d1\", \"_value_d2\"])\r\n    |> group(columns: [\"type\"])\r\ninput_data_rate = from(bucket: \"bucket1\")\r\n    |> range(start: timeRange)\r\n    // Check that this device is in the list of devices that we are looking for\r\n    |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n    |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\")\r\n    |> filter(fn: (r) => r._field == \"input_data_rate\")\r\n    |> window(every: 1m)\r\n    // Samples of 30 seconds have points that contain only power_in_a or only data for PM0 or PM1. Therefore, aggregate data over 1m to bring them together\r\n    |> mean()\r\n    |> duplicate(column: \"_stop\", as: \"_time\")\r\n    |> window(every: 1m)\r\n    // Samples of 30 seconds have points that contain only power_in_a or only data for PM0 or PM1. Therefore, aggregate data over 1m to bring them together\r\n    |> mean()\r\n    |> duplicate(column: \"_start\", as: \"_time\")\r\n    |> truncateTimeColumn(unit: 1m)\r\n    |> keep(columns: [\"_time\", \"_value\", \"source\", \"interface_name\"])\r\ninput_data_rate_if_up = join(\r\n    tables: {d1: interfaces_up, d2: input_data_rate},\r\n    on: [\"interface_name\", \"source\"],\r\n)\r\n\r\n// Unit: 1000s bps\r\ntotal_input_data_rate = input_data_rate_if_up\r\n    |> group(columns: [\"_time\", \"source\"])\r\n    |> sum(column: \"_value\")\r\n    // Sum over all interfaces\r\n    |> group()\r\n    |> group(columns: [\"source\"])\r\ncount_interfaces = interfaces_up\r\n    |> keep(columns: [\"interface_name\", \"source\"])\r\n    |> group(columns: [\"source\"])\r\n    |> count(column: \"interface_name\")\r\n    |> map(fn: (r) => ({r with _value: r.interface_name}))\r\n    |> keep(columns: [\"_value\", \"source\"])\r\ntotal_power_router = from(bucket: \"bucket1\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(\r\n        fn: (r) => r.device_type != \"cisco-8k\" and r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and r._field == \"total_pwr_output\",\r\n    )\r\n    |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            _value: float(v: r._value) * 0.1 + float(v: r._value),\r\n        // Workaround: consider +10% of the output as input power\r\n        }),\r\n    )\r\n    |> group()\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> unique(column: \"source\")\r\n    |> sort(columns: [\"source\"], desc: true)\r\n    |> truncateTimeColumn(unit: 1m)\r\n    |> group(columns: [\"_time\", \"source\"])\r\n    |> group(columns: [\"source\"])\r\n\r\n// Average router power / total input data rate (for all interfaces)\r\n// Unit: VA/Gbps (1000s bps /1000000)\r\naverage_power_consumption_ratio = join(\r\n    tables: {t1: total_power_router, t2: total_input_data_rate},\r\n    on: [\"_time\", \"source\"],\r\n)\r\n    |> map(\r\n        fn: (r) => ({r with\r\n            _value: \r\n                // Mark unused everything that has data rate < 100 kbps\r\n                if r._value_t2 > 100 then\r\n                    float(v: r._value_t1) / (float(v: r._value_t2) / 1000000.0)\r\n                else\r\n                    -1.0,\r\n        // mark as ununsed if traffic < 100kbps\r\n        }),\r\n    )\r\n    |> keep(columns: [\"_value\", \"source\"])\r\n    |> last()\r\n    |> group()\r\n    |> rename(columns: {_value: \"PCR\"})\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "NCS 55xx / NCS 5xx",
   "type": "table",
   "description": "Interfaces administratively up / down of type: .*IFT_.*HUNDREDGE, .*IFT_.*FORTY or .*IFT_.*TEN.\nPCR:Wattage per Gbps for interfaces with administrative state up.",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"influxdata/influxdb/v1\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = v1.measurementTagValues(\r\n  bucket: \"bucket1\",\r\n  measurement: \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\",\r\n  tag: \"source\"\r\n)\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"_value\")\r\n\r\nfrom(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\" or r[\"_field\"] == \"input_data_rate\")\r\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\r\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\r\n\r\n  // Take the mean of bandwidth and input_data_rate\r\n  |> window(every: timeInterval)\r\n  |> mean()\r\n\r\n  // Reshape\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> last(column: \"_value\")\r\n  |> group(columns: [\"source\", \"_field\"])\r\n\r\n  // Take the sum of bandwidths and input_data_rate for each device\r\n  |> aggregateWindow(every: timeInterval, fn: sum)\r\n\r\n  // Reshape\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> truncateTimeColumn(unit: timeInterval)\r\n  |> last()\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n\r\n  // Consider only data that has bandwidth greater than 0 and fill missing values of traffic data with 0\r\n  |> filter(fn: (r) => r.bandwidth > 0)\r\n\r\n  // Compute bandwidth utilization [0-1]\r\n  |> map(fn: (r) => ({ r with bandwidth_utilization: float(v: r[\"input_data_rate\"]) / float(v: r[\"bandwidth\"])}))\r\n\r\n  |> drop(columns: [\"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"source\"], desc: true)"
    },
    {
     "query": "import \"math\"\r\nimport \"influxdata/influxdb/v1\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = v1.measurementTagValues(\r\n  bucket: \"bucket1\",\r\n  measurement: \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\",\r\n  tag: \"source\"\r\n)\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"_value\")\r\n\r\ntype = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"type\")\r\n  |> filter(fn: (r) =>  r._value =~ /.*IFT_.*HUNDREDGE.*/ or r._value =~ /.*IFT_.*FORTY.*/ or r._value =~ /.*IFT_.*TEN.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_type: if r._field == \"type\" then r._value\r\n    else \"test\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_time\", \"_value\"])\r\n  |> distinct(column: \"if_type\")\r\n\r\nstate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"state\")\r\n  |> filter(fn: (r) => r._value =~ /.*up.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: if r._field == \"state\" then r._value\r\n    else \"NA\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\",  \"_field\", \"_time\"])\r\n  |> last()\r\n \r\ninterfaces_up = join(\r\n\ttables: {d1: state, d2: type},\r\n    on: [\"interface_name\", \"source\"],\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: r._value_d1,\r\n    if_type: r._value_d2\r\n   }))\r\n  |> drop(columns: [\"_value_d1\", \"_value_d2\"])\r\n  |> group(columns: [\"type\"])\r\n\r\n\r\ninput_data_rate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\")\r\n  |> filter(fn: (r) => r._field == \"input_data_rate\")\r\n  |>last()\r\n  |> keep(columns: [\"_time\", \"_value\" \"source\", \"interface_name\"])\r\n\r\ninput_data_rate_if_up = join(\r\n\ttables: {d1: interfaces_up, d2: input_data_rate},\r\n    on: [\"interface_name\", \"source\"],\r\n)\r\n\r\n// Unit: 1000s bps (1kbps)\r\ntotal_input_data_rate = input_data_rate_if_up\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n  |> sum()\r\n  |> keep(columns: [\"_time\", \"_value\" \"source\"])\r\n\r\ncount_interfaces = interfaces_up\r\n  |> keep(columns: [\"interface_name\", \"source\"])\r\n  |> group(columns: [\"source\"])\r\n  |> count(column: \"interface_name\")\r\n  |> map(fn: (r) => ({ r with _value: r.interface_name }))\r\n  |> keep(columns: [\"_value\", \"source\"])\r\n\r\n// POWER\r\n\r\nall = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\")\r\n  |> filter(\r\n      fn: (r) => (r._field == \"system_power_input\" and \r\n          // NCS 55A2, NCS550x: chassis-level reading\r\n          r.location =~ /^[0-9]$/) or \r\n          //r._field == \"system_power_used\" // or\r\n          (r._field == \"power_consumed_value_int\" and \r\n              // NCS550x: LC-level reading\r\n              r.location =~ /^[0-9]\\/[0-9]$/\r\n              // Select only locations that are of the form 0/0, 0/1, 0/2, ..., 0/9 (corresponding to LCs)\r\n              ),\r\n  )\r\n  |> keep(\r\n      columns: [\r\n          \"_field\",\r\n          \"_value\",\r\n          \"_time\",\r\n          \"source\",\r\n          \"system_power_input\",\r\n          \"power_consumed_value_int\",\r\n          \"location\",\r\n      ],\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: int(v: r._value) })) // Convert string to integers\r\n\r\n// Will add up the values for both LCs and chassis readings. This is wrong and has\r\n// to be corrected by later subtracting the router reading for the devices that\r\n// can directly provide readings per LCs.\r\n// There is no way to do it in a cleaner way (meaning, to separate the devices\r\n// that give the LC readings versus the chassis readings).\r\ntotal_power_router_PLUS_LCs = all\r\n  |> last()\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n  |> sum()\r\n\r\ntotal_power_router = all\r\n  |> filter(fn: (r) =>\r\n        r._field == \"system_power_input\" and\r\n        r.location =~ /^[0-9]$/\r\n    )\r\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"system_power_input\", \"location\"])\r\n  |> last()\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n  |> sum()\r\n\r\n// Power readings:\r\n// NCS 550x: at LC-level\r\n// NCS 55A2, NCS550x: at chassis-level\r\n// => final ones\r\n// NCS 550x: at LC-level\r\n// NCS 55A2: at chassis-level\r\ntotal_power_router_OR_LCs = join(\r\n\ttables: {d1: total_power_router_PLUS_LCs, d2: total_power_router},\r\n    on: [\"source\"],\r\n\t)\r\n  |> map(fn: (r) => ({\r\n    r with _value: // Check if there were both router and LCs added up. If so, remove the router reading.\r\n      if r._value_d1 > r._value_d2 then r._value_d1 - r._value_d2\r\n      else r._value_d1\r\n      })\r\n  )\r\n  |> keep(columns: [\"_value\", \"source\"])\r\n\r\n\r\n// Average router power / total input data rate (for all interfaces)\r\n// Unit: W/Gbps (1000s bps /1000000)\r\naverage_power_consumption_ratio = join(\r\n\ttables: {t1: total_power_router_OR_LCs, t2: total_input_data_rate},\r\n    on: [\"source\"],\r\n\t)\r\n    |> map(fn: (r) => ({\r\n    r with\r\n       _value:\r\n        // Mark unused everything that has data rate < 100 kbps\r\n        if r._value_t2 > 100 then float(v: r._value_t1) / (float(v: r._value_t2) / 1000000.0)\r\n        else -1.0, // mark as ununsed if traffic < 100kbps\r\n    \t_time: r._time_t1\r\n\t}))\r\n    |> keep(columns: [\"_value\", \"_time\", \"source\", \"subscription\", \"_measurement\"])\r\n    |> last()\r\n    |> group()\r\n    |> rename(columns: {_value: \"PCR\"})\r\n    |> yield()"
    },
    {
     "query": "import \"generate\"\n\npower = 1000.0\n\n// W\nbps_to_kbps = 1000.0\nkbps_to_gbps = 1000000.0\nnumber_of_kbps = 10000\n\n// 10 Gbps\nnumber_of_gbps = 1000.0\n\n// 1 Tbps\nbandwidth = number_of_gbps * kbps_to_gbps\n\n// unit: Kbps; 1000 Gbps = 1 Tbps\ngenerate.from(\n    count: 1,\n    fn: (n) => (n+1)*75 * number_of_kbps * int(v: bps_to_kbps),    // unit: Kbps; n * 10000 Kbps = n * 10 Gbps\n    start: -30m,\n    stop: -1s,\n)\n    |> map(fn: (r) => ({r with input_data_rate: float(v: r._value)}))\n    |> map(fn: (r) => ({r with bandwidth: bandwidth}))\n    |> map(fn: (r) => ({r with bandwidth_utilization: r.input_data_rate / r.bandwidth}))\n    |> map(fn: (r) => ({r with power: power}))\n    |> map(fn: (r) => ({r with PCR: r.power / (r.input_data_rate / kbps_to_gbps)}))\n    |> map(fn: (r) => ({r with source: \"Berlin-100\"}))\n    |> drop(columns: [\"_value\", \"_time\", \"power\"])"
    }
   ]
  },
  {
   "title": "ASR 9000",
   "type": "table",
   "description": "Interfaces administratively up / down of type: .*IFT_.*HUNDREDGE, .*IFT_.*FORTY or .*IFT_.*TEN.\nPCR:Wattage per Gbps for interfaces with administrative state up.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"influxdata/influxdb/v1\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set: ASR9Ks\r\ndevices = v1.measurementTagValues(\r\n  bucket: \"bucket1\",\r\n  measurement: \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\",\r\n  tag: \"source\"\r\n)\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"_value\")\r\n\r\nfrom(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\" or r[\"_field\"] == \"input_data_rate\")\r\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\r\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\r\n\r\n  // Take the mean of bandwidth and input_data_rate\r\n  |> window(every: timeInterval)\r\n  |> mean()\r\n\r\n  // Reshape\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> last(column: \"_value\")\r\n  |> group(columns: [\"source\", \"_field\"])\r\n\r\n  // Take the sum of bandwidths and input_data_rate for each device\r\n  |> aggregateWindow(every: timeInterval, fn: sum)\r\n\r\n  // Reshape\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> truncateTimeColumn(unit: timeInterval)\r\n  |> last()\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n\r\n  // Consider only data that has bandwidth greater than 0 and fill missing values of traffic data with 0\r\n  |> filter(fn: (r) => r.bandwidth > 0)\r\n\r\n  // Compute bandwidth utilization [0-1]\r\n  |> map(fn: (r) => ({ r with bandwidth_utilization: float(v: r[\"input_data_rate\"]) / float(v: r[\"bandwidth\"])}))\r\n\r\n  |> drop(columns: [\"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"source\"], desc: true)"
    },
    {
     "query": "import \"math\"\r\nimport \"influxdata/influxdb/v1\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set: ASR9Ks\r\ndevices = v1.measurementTagValues(\r\n  bucket: \"bucket1\",\r\n  measurement: \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\",\r\n  tag: \"source\"\r\n)\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"_value\")\r\n\r\ntype = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"type\")\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) =>  r._value =~ /.*IFT_.*HUNDREDGE.*/ or r._value =~ /.*IFT_.*FORTY.*/ or r._value =~ /.*IFT_.*TEN.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_type: if r._field == \"type\" then r._value\r\n    else \"test\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_time\", \"_value\"])\r\n  |> distinct(column: \"if_type\")\r\n\r\nstate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"state\")\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._value =~ /.*up.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: if r._field == \"state\" then r._value\r\n    else \"NA\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\",  \"_field\", \"_time\"])\r\n  |> last()\r\n \r\ninterfaces_up = join(\r\n\ttables: {d1: state, d2: type},\r\n    on: [\"interface_name\", \"source\"],\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: r._value_d1,\r\n    if_type: r._value_d2\r\n   }))\r\n  |> drop(columns: [\"_value_d1\", \"_value_d2\"])\r\n  |> group(columns: [\"type\"])\r\n\r\n\r\ninput_data_rate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\")\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._field == \"input_data_rate\")\r\n  |>last()\r\n  |> keep(columns: [\"_time\", \"_value\" \"source\", \"interface_name\"])\r\n\r\ninput_data_rate_if_up = join(\r\n\ttables: {d1: interfaces_up, d2: input_data_rate},\r\n    on: [\"interface_name\", \"source\"],\r\n)\r\n\r\n// Unit: 1000s bps\r\ntotal_input_data_rate = input_data_rate_if_up\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n  |> sum()\r\n  |> keep(columns: [\"_time\", \"_value\" \"source\"])\r\n\r\n\r\ncount_interfaces = interfaces_up\r\n  |> keep(columns: [\"interface_name\", \"source\"])\r\n  |> group(columns: [\"source\"])\r\n  |> count(column: \"interface_name\")\r\n  |> map(fn: (r) => ({ r with _value: r.interface_name }))\r\n  |> keep(columns: [\"_value\", \"source\"])\r\n\r\n// From Router level?\r\ntotal_power_router=from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => \r\n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \r\n    (r._field == \"system_power_input\")\r\n    )\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"system_power_input\"])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> unique(column: \"source\")\r\n\r\n// Average router power / total input data rate (for all interfaces)\r\n// Unit: W/Gbps (1000s bps /1000000)\r\naverage_power_consumption_ratio=join(\r\n\ttables: {t1: total_power_router, t2: total_input_data_rate},\r\n    on: [\"source\"],\r\n\t)\r\n    |> map(fn: (r) => ({\r\n    r with\r\n     _value:\r\n        // Mark unused everything that has data rate < 100 kbps\r\n        if r._value_t2 > 100 then float(v: r._value_t1) / (float(v: r._value_t2) / 1000000.0)\r\n        else -1.0, // mark as ununsed if traffic < 100kbps\r\n    \t_time: r._time_t1\r\n\t}))\r\n    |> keep(columns: [\"_value\", \"_time\", \"source\", \"subscription\", \"_measurement\"])\r\n    |> last()\r\n    |> group()\r\n    |> rename(columns: {_value: \"PCR\"})\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "ASR 9000 (32-bit)",
   "type": "table",
   "description": "Interfaces administratively up / down of type: .*IFT_.*HUNDREDGE, .*IFT_.*FORTY or .*IFT_.*TEN.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "8000 series",
   "type": "table",
   "description": "Interfaces administratively up / down of type: .*IFT_.*HUNDREDGE, .*IFT_.*FORTY or .*IFT_.*TEN.\nPCR:Wattage per Gbps for interfaces with administrative state up.",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/v1\"\r\nimport \"math\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => \r\n  \tr._measurement == \"Cisco-IOS-XR-invmgr-oper:inventory/entities/entity/attributes/inv-basic-bag\" \r\n    )\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  |> unique(column: \"source\")\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"source\")\r\n\r\nfrom(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\" or r[\"_field\"] == \"input_data_rate\")\r\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\r\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\r\n\r\n  // Take the mean of bandwidth and input_data_rate\r\n  |> window(every: timeInterval)\r\n  |> mean()\r\n\r\n  // Reshape\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> last(column: \"_value\")\r\n  |> group(columns: [\"source\", \"_field\"])\r\n\r\n  // Take the sum of bandwidths and input_data_rate for each device\r\n  |> aggregateWindow(every: timeInterval, fn: sum)\r\n\r\n  // Reshape\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> truncateTimeColumn(unit: timeInterval)\r\n  |> last()\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n\r\n  // Consider only data that has bandwidth greater than 0 and fill missing values of traffic data with 0\r\n  |> filter(fn: (r) => r.bandwidth > 0)\r\n\r\n  // Compute bandwidth utilization [0-1]\r\n  |> map(fn: (r) => ({ r with bandwidth_utilization: float(v: r[\"input_data_rate\"]) / float(v: r[\"bandwidth\"])}))\r\n\r\n  |> drop(columns: [\"_time\"])\r\n  |> group()\r\n  |> sort(columns: [\"source\"], desc: true)"
    },
    {
     "query": "import \"influxdata/influxdb/v1\"\r\nimport \"math\"\r\ntimeRange = -10m\r\ntimeInterval = 5m\r\n\r\n// Gather names of devices in a set\r\ndevices = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  |> filter(fn: (r) => \r\n  \tr._measurement == \"Cisco-IOS-XR-invmgr-oper:inventory/entities/entity/attributes/inv-basic-bag\" \r\n    )\r\n  // Trick to enforce grouping by same key of all devices\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    groupingkey: 1\r\n   }))\r\n  |> group(columns: [\"groupingkey\"])\r\n  |> unique(column: \"source\")\r\n  // Extract a set with the names of the devices\r\n  |> findColumn(fn: (key) => key.groupingkey == 1, column: \"source\")\r\n\r\ntype = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"type\")\r\n  |> filter(fn: (r) =>  r._value =~ /.*IFT_.*HUNDREDGE.*/ or r._value =~ /.*IFT_.*FORTY.*/ or r._value =~ /.*IFT_.*TEN.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_type: if r._field == \"type\" then r._value\r\n    else \"test\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_time\", \"_value\"])\r\n  |> distinct(column: \"if_type\")\r\n\r\nstate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\" and r._field == \"state\")\r\n  |> filter(fn: (r) => r._value =~ /.*up.*/)\r\n  |> drop(columns: [\"subscription\", \"host\", \"path\", \"_measurement\"])\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: if r._field == \"state\" then r._value\r\n    else \"NA\"\r\n   }))\r\n  |> group(columns: [\"interface_name\", \"source\"])\r\n  |> drop(columns: [\"_start\", \"_stop\",  \"_field\", \"_time\"])\r\n  |> last()\r\n \r\ninterfaces_up = join(\r\n\ttables: {d1: state, d2: type},\r\n    on: [\"interface_name\", \"source\"],\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    if_state: r._value_d1,\r\n    if_type: r._value_d2\r\n   }))\r\n  |> drop(columns: [\"_value_d1\", \"_value_d2\"])\r\n  |> group(columns: [\"type\"])\r\n\r\n\r\ninput_data_rate = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\")\r\n  |> filter(fn: (r) => r._field == \"input_data_rate\")\r\n  |> window(every: 1m) // Samples of 30 seconds have points that contain only power_in_a or only data for PM0 or PM1. Therefore, aggregate data over 1m to bring them together\r\n  |> mean()\r\n  |> duplicate(column: \"_stop\", as: \"_time\")\r\n  |> window(every: 1m) // Samples of 30 seconds have points that contain only power_in_a or only data for PM0 or PM1. Therefore, aggregate data over 1m to bring them together\r\n  |> mean()\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> truncateTimeColumn(unit: 1m)\r\n  |> keep(columns: [\"_time\", \"_value\" \"source\", \"interface_name\"])\r\n\r\ninput_data_rate_if_up = join(\r\n\ttables: {d1: interfaces_up, d2: input_data_rate},\r\n    on: [\"interface_name\", \"source\"],\r\n)\r\n\r\n// Unit: 1000s bps\r\ntotal_input_data_rate = input_data_rate_if_up\r\n  |> group(columns: [\"_time\", \"source\"])\r\n  |> sum(column: \"_value\") // Sum over all interfaces\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n\r\n\r\ncount_interfaces = interfaces_up\r\n  |> keep(columns: [\"interface_name\", \"source\"])\r\n  |> group(columns: [\"source\"])\r\n  |> count(column: \"interface_name\")\r\n  |> map(fn: (r) => ({ r with _value: r.interface_name }))\r\n  |> keep(columns: [\"_value\", \"source\"])\r\n\r\ntotal_power_router = from(bucket: \"bucket1\")\r\n  |> range(start: timeRange)\r\n  // Check that this device is in the list of devices that we are looking for\r\n  |> filter(fn: (r) => contains(value: r.source, set: devices))\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \r\n    (\r\n    r._field == \"pem_info_array/current_in_a\" or\r\n    r._field == \"pem_info_array/voltage_in_a\" or \r\n    r._field == \"pem_info_array/current_in_b\" or\r\n    r._field == \"pem_info_array/voltage_in_b\"\r\n    )\r\n    and contains(value: r.source, set: devices))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\r\n\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    power_in_a: if float(v: r.current_in_a) > 100 then (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0) else (float(v: r.voltage_in_a)) * (float(v: r.current_in_a)),\r\n    power_in_b: if float(v: r.current_in_b) > 100 then (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0) else (float(v: r.voltage_in_b)) * (float(v: r.current_in_b)),\r\n   }))\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: r.power_in_a + r.power_in_b,\r\n  }))\r\n  |> window(every: 1m) // Samples of 30 seconds have points that contain only power_in_a or only data for PM0 or PM1. Therefore, aggregate data over 1m to bring them together\r\n  |> mean()\r\n  |> duplicate(column: \"_start\", as: \"_time\")\r\n  |> truncateTimeColumn(unit: 1m)\r\n  |> group(columns: [\"_time\", \"source\"])\r\n  |> sum(column: \"_value\") // Sum over all tags (e.g. the PM nodes)\r\n  |> group()\r\n  |> group(columns: [\"source\"])\r\n\r\n// Average router power / total input data rate (for all interfaces)\r\n// Unit: VA/Gbps (1000s bps /1000000)\r\naverage_power_consumption_ratio = join(\r\n\ttables: {t1: total_power_router, t2: total_input_data_rate},\r\n    on: [\"_time\", \"source\"],\r\n\t)\r\n    |> map(fn: (r) => ({\r\n    r with\r\n       _value:\r\n        // Mark unused everything that has data rate < 100 kbps\r\n        if r._value_t2 > 100 then float(v: r._value_t1) / (float(v: r._value_t2) / 1000000.0)\r\n        else -1.0, // mark as ununsed if traffic < 100kbps\r\n\t}))\r\n    |> keep(columns: [\"_value\", \"source\"])\r\n    |> last()\r\n    |> group()\r\n    |> rename(columns: {_value: \"PCR\"})\r\n    |> yield()"
    }
   ]
  },
  {
   "title": "${Device}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "Device",
   "targets": [
    {}
   ]
  },
  {
   "title": "Bandwidth utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "timeInterval = 5m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Device}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\" or r[\"_field\"] == \"input_data_rate\")\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\n  |> truncateTimeColumn(unit: timeInterval)\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\n  |> group()\n\n  // Consider only data that has bandwidth greater than 0 and fill missing values of traffic data with 0\n  |> filter(fn: (r) => r.bandwidth > 0)\n  //|> fill(column: \"input_data_rate\", value: 0)\n  // Compute bandwidth utilization [0-1]\n  |> map(fn: (r) => ({ r with bandwidth_utilization: float(v: r[\"input_data_rate\"]) / float(v: r[\"bandwidth\"])}))\n\n  // Aggregate data\n  |> group(columns: [\"source\", \"interface_name\"])\n  |> aggregateWindow(every: timeInterval, fn: last, column: \"bandwidth_utilization\", createEmpty: false)\n  |> drop(columns: [\"_start\", \"_stop\", \"bandwidth\", \"input_data_rate\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "timeInterval = 5m\n\nfrom(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Device}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/total/data-rate\" or r[\"_measurement\"] == \"Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-briefs/interface-brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\")\n  |> filter(fn: (r) =>  r.interface_name =~ /.*HundredGigE.*/ or r.interface_name =~ /.*FortyGigE.*/ or r.interface_name =~ /.*TenGigE.*/)\n  |> drop(columns: [\"path\", \"subscription\", \"_measurement\", \"host\"])\n  |> truncateTimeColumn(unit: timeInterval)\n  |> last()\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"_field\"])\n"
    }
   ]
  }
 ]
}