{
 "title": "Power",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nexus 3K, 92xx, 93xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 36, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_input_actual_draw\"\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pIn\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"name\"])\n  |> keep(columns: [\"pIn\", \"name\", \"_time\"])\n  |> sum(column: \"pIn\")\n  |> group(columns: [\"name\"])\n  |> last(column: \"pIn\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"name\"], valueColumn: \"pIn\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 36, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_capacity\"\n    ))\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply efficiency",
   "type": "gauge",
   "gridPos": { "h": 36, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and \n    (\n    r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" or \n    r._field == \"powersup/power_summary/tot_pow_out_actual_draw\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r[\"powersup/power_summary/tot_pow_out_actual_draw\"]) / float(v: r[\"powersup/power_summary/tot_pow_input_actual_draw\"])) * 100.0\n  }))\n  |> drop(columns: [\"powersup/power_summary/tot_pow_out_actual_draw\", \"powersup/power_summary/tot_pow_input_actual_draw\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "pIn = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pIn\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"name\"])\n  |> keep(columns: [\"pIn\", \"name\", \"_time\"])\n  |> sum(column: \"pIn\")\n  |> group(columns: [\"name\"])\n  |> last(column: \"pIn\")\n\npOut = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pOut\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"name\"])\n  |> keep(columns: [\"pOut\", \"name\", \"_time\"])\n  |> sum(column: \"pOut\")\n  |> group(columns: [\"name\"])\n  |> last(column: \"pOut\")\n\nj = join(\n\ttables: {t1: pIn, t2: pOut},\n    on: [\"name\", \"_time\"],\n\t)\n  |> map(fn: (r) => ({\n    r with\n      _value: float(v: r.pOut) / float(v: r.pIn) * 100.0,\n  }))\n  |> keep(columns: [\"_value\", \"_time\", \"name\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "Power supply load",
   "type": "gauge",
   "gridPos": { "h": 36, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and \n    (\n    r._field == \"powersup/power_summary/tot_pow_capacity\" or \n    r._field == \"powersup/power_summary/tot_pow_out_actual_draw\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r[\"powersup/power_summary/tot_pow_out_actual_draw\"]) / float(v: r[\"powersup/power_summary/tot_pow_capacity\"])) * 100.0\n  }))\n  |> drop(columns: [\"powersup/power_summary/tot_pow_out_actual_draw\", \"powersup/power_summary/tot_pow_capacity\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "NCS5xx, NCS5xxx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 34, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n    (\n    r._field == \"system_power_input\" //or \n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    r._field == \"total_pwr_output\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r._value) * 0.1 + float(v: r._value)) // Workaround: consider +10% of the output as input power\n   }))\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 34, "w": 3, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n    (\n    r._field == \"power_resrv_and_alloc\"\n    ))\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and \n    (\n    //r._field == \"total_pwr_input\" or\n    //r._field == \"total_pwr_output\" or\n    //r._field == \"total_output_capacity\" or\n    r._field == \"total_pwr_required\"\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply efficiency",
   "type": "gauge",
   "gridPos": { "h": 34, "w": 3, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n    (\n    r._field == \"system_power_input\" or \n    r._field == \"system_power_used\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.pem == \"0\" or r.pem == \"1\" or r.pem == \"3\")\n  |> filter(fn: (r) => r.system_power_input > 0)\n  |> filter(fn: (r) => r.system_power_used != 0)\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.system_power_used) / float(v: r.system_power_input)) * 100.0\n   }))\n  |> drop(columns: [\"system_power_used\", \"system_power_input\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    r._field == \"total_pwr_output\" and r._value > 0\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v:r._value) / (float(v: r._value) * 0.1 + float(v: r._value))) * 100.0 // Workaround: consider +10% of the output as input power\n   }))\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply load",
   "type": "gauge",
   "gridPos": { "h": 34, "w": 3, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"usable_power_capacity\" or \n    r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_used\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.pem == \"0\" or r.pem == \"1\" or r.pem == \"3\")\n  |> filter(fn: (r) => r.usable_power_capacity > 0 or r.protection_power_capacity > 0)\n  |> filter(fn: (r) => r.system_power_used != 0)\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.system_power_used) / float(v: r.usable_power_capacity + r.protection_power_capacity)) * 100.0\n   }))\n  |> drop(columns: [\"system_power_used\", \"usable_power_capacity\", \"protection_power_capacity\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    (r._field == \"total_pwr_output\" or r._field == \"total_out_capacity\") and r._value > 0\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({\n    r with\n    _value: float(v: r.total_pwr_output) / float(v: r.total_out_capacity) * 100.0\n   }))\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "ASR 9K",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 13, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"system_power_input\"\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"system_power_input\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 21, "w": 3, "x": 13, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_resrv_and_alloc\"\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply efficiency",
   "type": "gauge",
   "gridPos": { "h": 21, "w": 3, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"system_power_input\" or \n    r._field == \"system_power_used\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.pem == \"0\" or r.pem == \"1\" or r.pem == \"3\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.system_power_used) / float(v: r.system_power_input)) * 100.0\n  }))\n  |> drop(columns: [\"system_power_used\", \"system_power_input\", \"country\", \"region\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply load",
   "type": "gauge",
   "gridPos": { "h": 21, "w": 3, "x": 19, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"usable_power_capacity\" or \n    r._field == \"protection_power_capacity\" or \n    r._field == \"system_power_used\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.pem == \"0\" or r.pem == \"1\" or r.pem == \"3\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.system_power_used) / float(v: r.usable_power_capacity + r.protection_power_capacity)) * 100.0\n   }))\n  |> drop(columns: [\"system_power_used\", \"usable_power_capacity\", \"protection_power_capacity\", \"country\", \"region\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "ASR 9K (32-bit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r.voltage1 * r.current1 + r.voltage2 * r.current2) / 1000000}))\n  |> keep(columns: [\"_time\", \" \", \"source\"])"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 13, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r.capacity1 + r.capacity2)}))\n  |> keep(columns: [\"_time\", \" \", \"source\"])"
      }
     ]
    },
    {
     "title": "Power supply efficiency",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Power supply load",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \"capacity_power\": (r.capacity1 + r.capacity2)}))\n  |> map(fn: (r) => ({r with \"output_power\": (r.voltage1 * r.current1 + r.voltage2 * r.current2) / 1000000}))\n  |> keep(columns: [\"capacity_power\", \"output_power\", \"source\"])\n  |> map(fn: (r) => ({r with \"_value\": float(v: r.output_power) / float(v:r.capacity_power) * 100.0}))\n  |> keep(columns: [\"_time\", \"_value\", \"source\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "C8K",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input power",
   "type": "bargauge",
   "description": "Efficiency may be low if the power supply is at very low operation range (e.g. 100W for a 4kW power supply)",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/current_in_a\" or\n    r._field == \"pem_info_array/voltage_in_a\" or \n    r._field == \"pem_info_array/current_in_b\" or\n    r._field == \"pem_info_array/voltage_in_b\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\n  |> map(fn: (r) => ({\n    r with\n    power_in_a: if float(v: r.current_in_a) > 100 then (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0) else (float(v: r.voltage_in_a)) * (float(v: r.current_in_a)),\n    power_in_b: if float(v: r.current_in_b) > 100 then (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0) else (float(v: r.voltage_in_b)) * (float(v: r.current_in_b)),\n   }))\n  |> map(fn: (r) => ({\n    r with\n    _value: r.power_in_a + r.power_in_b,\n  }))\n  |> last(column: \"_value\")\n  |> group(columns:[\"source\"])\n  |> keep(columns: [\"in_power\", \"_field\", \"_value\", \"source\"])\n  |> sum(column: \"_value\")\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 13, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and \n    (\n    r._field == \"total_pwr_required\"\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Power supply efficiency",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "power_in = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/current_in_a\" or\n    r._field == \"pem_info_array/voltage_in_a\" or \n    r._field == \"pem_info_array/current_in_b\" or\n    r._field == \"pem_info_array/voltage_in_b\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\n  |> map(fn: (r) => ({\n    r with\n    power_in_a: if float(v: r.current_in_a) > 100 then (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0) else (float(v: r.voltage_in_a)) * (float(v: r.current_in_a)),\n    power_in_b: if float(v: r.current_in_b) > 100 then (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0) else (float(v: r.voltage_in_b)) * (float(v: r.current_in_b)),\n   }))\n  |> map(fn: (r) => ({\n    r with\n    total_power_in: r.power_in_a + r.power_in_b,\n  }))\n  |> last(column: \"total_power_in\")\n  |> keep(columns: [\"total_power_in\", \"_field\", \"_value\", \"source\"])\n  |> reduce(fn: (r, accumulator) => ({ sum: float(v: r.total_power_in) + accumulator.sum }), identity: {sum: 0.0})\n\npower_out = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/voltage_out\" or\n    r._field == \"pem_info_array/current_out\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_out\": \"voltage_out\", \"pem_info_array/current_out\": \"current_out\"})\n  |> keep(columns: [\"voltage_out\", \"current_out\", \"_field\", \"_value\", \"_time\", \"node\", \"name\", \"pem_info_array/node_name\", \"pem_info_array/node_type\", \"pem_info_array/node_status\", \"source\"])\n  |> map(fn: (r) => ({\n    r with\n    power_out: if float(v: r.current_out) > 100 then (float(v: r.voltage_out)/1000.0) * (float(v: r.current_out)/1000.0) else float(v: r.voltage_out)*float(v: r.current_out),\n   }))\n  |> last(column: \"power_out\")\n  |> keep(columns: [\"power_out\", \"_field\", \"_value\", \"_time\", \"source\"])\n  |> reduce(fn: (r, accumulator) => ({ sum: float(v: r.power_out) + accumulator.sum }), identity: {sum: 0.0})\n\njoin(\n\ttables: {d1: power_in, d2: power_out},\n    on: [\"source\"],\n)\n\n  |> map(fn: (r) => ({\n    r with\n    power_in: r.sum_d1,\n    power_out: r.sum_d2\n   }))\n  |> map(fn: (r) => ({\n    r with\n    power_eff: (r.power_out / r.power_in) * 100.0\n   }))\n  |> drop(columns: [\"sum_d1\", \"sum_d2\", \"power_in\", \"power_out\"])\n  |> group(columns: [\"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[], columnKey: [\"source\"], valueColumn: \"power_eff\")"
    }
   ]
  },
  {
   "title": "Power supply load",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 19, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "power_capacity = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-invmgr-oper:inventory/entities/entity/attributes/inv-basic-bag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power_capacity\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column: \"power_capacity\")\n  |> keep(columns: [\"power_capacity\", \"_field\", \"_value\", \"source\"])\n  |> reduce(fn: (r, accumulator) => ({ sum: float(v: r.power_capacity) + accumulator.sum }), identity: {sum: 0.0})\n\npower_out = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/voltage_out\" or\n    r._field == \"pem_info_array/current_out\"\n    )\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_out\": \"voltage_out\", \"pem_info_array/current_out\": \"current_out\"})\n  |> keep(columns: [\"voltage_out\", \"current_out\", \"_field\", \"_value\", \"_time\", \"node\", \"name\", \"pem_info_array/node_name\", \"pem_info_array/node_type\", \"pem_info_array/node_status\", \"source\"])\n  |> map(fn: (r) => ({\n    r with\n    power_out: if float(v: r.current_out) > 100 then (float(v: r.voltage_out)/1000.0) * (float(v: r.current_out)/1000.0) else float(v: r.voltage_out) * float(v: r.current_out),\n   }))\n  |> last(column: \"power_out\")\n  |> keep(columns: [\"power_out\", \"_field\", \"_value\", \"_time\", \"source\"])\n  |> reduce(fn: (r, accumulator) => ({ sum: float(v: r.power_out) + accumulator.sum }), identity: {sum: 0.0})\n\njoin(\n\ttables: {d1: power_capacity, d2: power_out},\n    on: [\"source\"],\n)\n\n  |> map(fn: (r) => ({\n    r with\n    power_capacity: r.sum_d1,\n    power_out: r.sum_d2\n   }))\n  |> map(fn: (r) => ({\n    r with\n    power_supply_load: (r.power_out / r.power_capacity) * 100.0\n   }))\n  |> drop(columns: [\"sum_d1\", \"sum_d2\", \"power_capacity\", \"power_out\"])\n  |> group(columns: [\"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[], columnKey: [\"source\"], valueColumn: \"power_supply_load\")"
    }
   ]
  },
  {
   "title": "ASR 9xx (IOS XE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and (r.name == \"PEM Iout\" or r.name == \"PEM Vout\"))\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"name\"], rowKey: [\"source\", \"location\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r[\"PEM Iout\"] * r[\"PEM Vout\"])}))\n  |> group(columns: [\"source\"])\n  |> sum(column: \" \")"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 13, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and (r.name == \"PEM Iout\" or r.name == \"PEM Vout\"))\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"name\"], rowKey: [\"source\", \"location\"], valueColumn: \"_value\")\n  |> group(columns: [\"source\"])\n  |> map(fn:(r) => ({r with \" \": int(v: r.maxpower)}))\n  |> sum(column: \" \")"
      }
     ]
    },
    {
     "title": "Power supply efficiency",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Power supply load",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}